name: Acquire activation file
on:
  push:
  pull_request:
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Request Activation File
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2.0-alpha-1
      
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
        
  checkout:
    name: CheckOut
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        unityVersion: 2019.4.21f1
      with:
        githubToken: ${{ secrets.TOKEN }}
    - uses: game-ci/unity-test-runner@v2
      with:
        githubToken: ${{ secrets.TOKEN }}
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test results
        path: artifacts
